before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: C6Jc/IFEYKRu69DkZkhA7gitwkaCD+wjb92of+NYT4hgODKiGPsAxFKhCRqCnDNVvbh6Ie54l2FRb/Hn9QECJyd1Xl1R4NCgXynHIppkaJzgyYDZGRMpjimRRZNrEVcoy79L3z/4m07TL7KkxYvQqwugZim+0IMd8Wnh+ajTi1us8wKeqnUaIcR/aiXL84KLuwk/Cdnio/5pxjNmEOunOkgHdZMFQxDyAaqY6h5rF7FNCx8aea8NqFtnktR8/04iTE+ZYxMou0+AQg42MY9SCuwtT+nYZy0NGOgUJY2sMvGTSRnZaGxLJayhEJet8tNfV8NEx35uQFk1XnV6r4S0cGWUQqpaFXfuKFENRe1Qb5n2psHhbwwGyQezSAwOFVbUrFJcA+wvStw+ebPR6pc3MBKi/x4FYeGUx1MRhKbtR3EY2zQ7zpc28uoDXe9cT9wXE60WAztR0tZIqoRY/OJ0yGs9TkVq2aDASxOR3s74lZ8xgino0oqeaBEl4Ww/W3oQGGIKQnzxZu620W3B58mYL4gDXENKNEXEaDOxghe+L8iwIbJbvQekjhGZggdALQNNoQCGBEptlXbGCnk9Ou57f8n+nMUomxxt2K7CeAPaAnoB0ouVQsq9nu7F21HzRE3Lx2kWBOBMNlUHhS+UNt1KKaB8Av5a6oLfuHH1nEnfNuc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
